import elements.util.util as util

def oeuf(t, egg_color, dots_color):
    t.speed(100)

    # Contour noir
    util.row_right_squares(t, 4)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    util.double_high_traverse(t)
    util.row_left_squares(t, 2)
    util.row_right_squares(t, 4)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(40)
    t.right(90)
    util.row_right_squares(t, 2)
    util.left_square(t)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    util.right_square(t)
    t.forward(20)
    t.left(90)
    util.row_right_squares(t, 4)
    util.left_square(t)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    util.right_square(t)
    t.forward(40)
    t.left(90)
    util.row_left_squares(t, 2)
    util.row_right_squares(t, 2)
    util.walk_along_up_square(t)
    util.row_right_squares(t, 4)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    t.forward(20)
    util.walk_along_up_square(t)
    util.row_right_squares(t, 2)

    # Encrage
    t.color(egg_color)
    t.begin_fill()
    util.walk_along_up_square(t)
    t.forward(80)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    util.walk_along_up_square(t)
    t.forward(40)
    util.walk_along_up_square(t)
    t.forward(80)
    util.long_left_diagonal(t)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    t.right(90)
    util.low_traverse(t)
    util.walk_along_up_square(t)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.right(90)
    util.low_traverse(t)
    util.walk_along_up_square(t)
    t.forward(40)
    util.walk_along_up_square(t)
    t.forward(40)
    util.walk_along_up_square(t)
    t.forward(80)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    util.walk_along_up_square(t)
    t.forward(40)
    t.end_fill()

    # Pois inférieur gauche
    t.up()
    t.color(dots_color)
    t.backward(40)
    t.left(90)
    t.down()
    util.row_right_squares(t, 3)
    t.left(90)
    util.row_right_squares(t, 2)
    t.backward(20)
    t.left(90)
    util.row_left_squares(t, 2)

    # Pois inférieur droit
    t.up()
    t.left(90)
    t.forward(180)
    t.left(90)
    t.down()
    util.row_left_squares(t, 3)
    t.backward(60)
    util.row_right_squares(t, 4)
    t.right(90)
    t.forward(20)
    t.right(90)
    util.row_left_squares(t, 2)

    # Pois supérieur droit
    t.up()
    t.left(180)
    t.forward(80)
    t.down()
    util.row_left_squares(t, 2)
    t.backward(40)
    t.left(90)
    t.forward(40)
    t.right(90)
    util.row_right_squares(t, 4)
    t.left(180)
    util.row_right_squares(t, 3)

    # Pois supérieur gauche
    t.up()
    t.right(90)
    t.forward(100)
    t.down()
    util.row_right_squares(t, 2)
    t.right(90)
    util.row_right_squares(t, 3)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.left(180)
    util.row_right_squares(t, 4)
    t.left(180)
    t.forward(20)
    util.row_right_squares(t, 3)

    # Pois central
    t.up()
    t.left(180)
    t.forward(120)
    t.down()
    util.row_right_squares(t, 3)
    util.low_traverse(t)
    t.left(90)
    util.row_left_squares(t, 5)
    t.backward(100)
    util.row_right_squares(t, 5)
    util.double_right_linear_traverse(t)
    util.row_right_squares(t, 5)
    t.backward(80)
    util.row_left_squares(t, 3)