import util

def boo(t, bodyColor, mouthColor):
    t.speed(100)

    # Contour noir
    util.row_right_squares(t, 4)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(40)
    t.right(90)
    util.row_right_squares(t, 2)
    util.left_square(t)
    t.forward(20)
    t.left(90)
    t.forward(20)
    util.row_right_squares(t, 3)
    util.row_left_squares(t, 3)
    t.left(90)
    t.forward(40)
    t.right(90)
    util.row_right_squares(t, 2)
    util.left_square(t)
    util.long_left_diagonal(t)
    t.left(90)
    util.row_left_squares(t, 2)
    util.row_right_squares(t, 5)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.left(90)
    util.row_left_squares(t, 2)
    util.row_right_squares(t, 5)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    t.forward(20)
    util.walk_along_up_square(t)
    util.row_right_squares(t, 3)

    # Encrage du corps
    t.color(bodyColor)
    t.begin_fill()
    util.walk_along_up_square(t)
    t.forward(80)
    util.long_left_diagonal(t)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    util.walk_along_up_square(t)
    t.forward(60)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(60)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    util.walk_along_up_square(t)
    t.forward(40)
    util.walk_along_up_square(t)
    t.forward(100)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    util.walk_along_up_square(t)
    t.forward(40)
    util.walk_along_up_square(t)
    t.forward(100)
    util.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    util.walk_along_up_square(t)
    t.forward(60)
    t.end_fill()

    # Yeux
    t.up()
    t.color("black")
    t.left(90)
    t.forward(140)
    t.down()
    util.row_left_squares(t, 2)
    t.up()
    t.left(90)
    t.forward(40)
    t.left(90)
    t.down()
    util.row_right_squares(t, 2)

    # Main
    t.up()
    t.left(90)
    t.forward(100)
    t.down()
    util.right_square(t)
    t.forward(20)
    util.row_left_squares(t, 2)
    t.right(90)
    util.row_left_squares(t, 2)
    util.right_square(t)

    # Bouche
    t.up()
    t.forward(20)
    t.right(90)
    t.forward(100)
    t.down()
    t.color(mouthColor)
    util.row_left_squares(t, 5)
    t.left(180)
    util.row_left_squares(t, 5)
    t.right(90)
    t.forward(40)
    util.left_square(t)
    t.left(90)
    t.forward(20)
    t.left(180)
    util.row_right_squares(t, 5)
    t.left(90)
    util.left_square(t)
    t.left(90)
    t.forward(40)
    util.right_square(t)
    t.forward(20)
    t.left(90)
    t.forward(60)
    util.right_square(t)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    t.forward(40)
    util.right_square(t)