import util

def champignon(t, color):
    t.speed(100)

    # Contour noir
    t.down()
    t.right(90)
    util.row_right_squares(t, 2)
    util.left_square(t)
    util.low_traverse(t)
    util.row_right_squares(t, 8)
    util.left_square(t)
    util.low_traverse(t)
    util.row_right_squares(t, 3)
    t.right(90)
    util.row_right_squares(t, 2)
    t.left(90)
    util.row_right_squares(t, 6)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    util.double_high_traverse(t)
    util.row_left_squares(t, 2)
    util.row_right_squares(t, 7)
    t.backward(20)
    util.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    util.right_square(t)
    util.double_high_traverse(t)
    util.row_left_squares(t, 2)
    util.row_right_squares(t, 6)
    t.left(90)
    util.row_right_squares(t, 3)
    util.row_left_squares(t, 2)
    t.right(90)
    util.row_left_squares(t, 2)
    t.left(180)
    t.forward(40)
    t.right(90)
    util.row_left_squares(t, 3)
    t.right(90)
    util.row_left_squares(t, 2)
    t.left(180)
    t.forward(40)
    t.right(90)
    util.row_left_squares(t, 3)
    util.right_square(t)

    # Zone beige
    t.color("#FFC1A0")
    t.begin_fill()
    t.right(90)
    util.low_traverse(t)
    util.double_right_linear_traverse(t)
    util.low_traverse(t)
    t.right(90)
    t.forward(160)
    t.right(90)
    util.low_traverse(t)
    util.double_right_linear_traverse(t)
    util.low_traverse(t)
    util.double_right_linear_traverse(t)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    util.double_right_linear_traverse(t)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.end_fill()

    # Zone colorée
    t.color(color)
    t.begin_fill()
    t.forward(60)
    t.left(90)
    t.forward(120)
    t.left(90)
    util.double_high_traverse(t)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    util.double_high_traverse(t)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(160)
    t.right(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc inférieur droit
    t.left(180)
    t.forward(20)
    t.color("white")
    t.right(90)
    t.begin_fill()
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc supérieur droit
    t.up()
    t.left(180)
    t.forward(100)
    t.right(90)
    t.down()
    t.begin_fill()
    t.forward(40)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    util.low_traverse(t)
    t.right(90)
    util.low_traverse(t)
    t.end_fill()

    # Pois blanc central
    t.up()
    t.left(180)
    t.forward(60)
    t.left(90)
    t.down()
    t.begin_fill()
    t.forward(60)
    t.right(90)
    util.low_traverse(t)
    t.right(90)
    t.forward(60)
    t.right(90)
    util.low_traverse(t)
    t.right(90)
    t.forward(60)
    t.right(90)
    util.low_traverse(t)
    t.right(90)
    t.forward(60)
    t.right(90)
    util.low_traverse(t)
    t.end_fill()

    # Pois blanc supérieur gauche
    t.up()
    t.left(180)
    t.forward(120)
    t.down()
    t.begin_fill()
    t.forward(20)
    util.double_right_linear_traverse(t)
    util.low_traverse(t)
    util.double_right_linear_traverse(t)
    t.forward(20)
    t.right(90)
    util.low_traverse(t)
    t.right(90)
    util.low_traverse(t)
    t.end_fill()

    # Pois blanc inférieur gauche
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    t.forward(40)
    t.right(90)
    util.low_traverse(t)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(80)
    t.right(90)
    t.forward(20)
    t.right(90)
    util.low_traverse(t)
    t.end_fill()