from turtle import *
import util
import time

def champignon(t, color):
    # Contour noir
    t.speed(100)
    t.down()
    t.right(90)
    util.rowRightSquares(t, 2)
    util.leftSquare(t)
    t.forward(20)
    t.left(90)
    t.forward(20)
    util.rowRightSquares(t, 8)
    util.leftSquare(t)
    t.forward(20)
    t.left(90)
    t.forward(20)
    util.rowRightSquares(t, 3)
    t.right(90)
    util.rowRightSquares(t, 2)
    t.left(90)
    util.rowRightSquares(t, 6)
    util.rowLeftSquares(t, 2)
    t.left(90)
    t.forward(20)
    util.rightSquare(t)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.left(90)
    util.rowLeftSquares(t, 2)
    util.rowRightSquares(t, 7)
    t.backward(20)
    util.rowLeftSquares(t, 2)
    t.left(90)
    t.forward(20)
    util.rightSquare(t)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.left(90)
    util.rowLeftSquares(t, 2)
    util.rowRightSquares(t, 6)
    t.left(90)
    util.rowRightSquares(t, 3)
    util.rowLeftSquares(t, 2)
    t.right(90)
    util.rowLeftSquares(t, 2)
    t.left(180)
    t.forward(40)
    t.right(90)
    util.rowLeftSquares(t, 3)
    t.right(90)
    util.rowLeftSquares(t, 2)
    t.left(180)
    t.forward(40)
    t.right(90)
    util.rowLeftSquares(t, 3)
    util.rightSquare(t)

    # Zone beige
    t.color("#FFC1A0")
    t.begin_fill()
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(160)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.end_fill()

    # Zone rouge
    t.color(color)
    t.begin_fill()
    t.forward(60)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(160)
    t.right(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc inférieur droit
    t.left(180)
    t.forward(20)
    t.color("white")
    t.right(90)
    t.begin_fill()
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc supérieur droit
    t.up()
    t.left(180)
    t.forward(100)
    t.right(90)
    t.down()
    t.begin_fill()
    t.forward(40)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc central
    t.up()
    t.left(180)
    t.forward(60)
    t.left(90)
    t.down()
    t.begin_fill()
    t.forward(60)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc supérieur gauche
    t.up()
    t.left(180)
    t.forward(120)
    t.down()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc inférieur gauche
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(80)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.end_fill()

    time.sleep(5)

t = Turtle()
champignon(t, "#1BD50B")