from usefull.usefull import *


def bill_balle(t, type_color, pixel_size):
    t.speed(100)

    if type_color == 1:
        color = "#000000"
    else:
        color = "#FFD700"

    # Corps
    t.color(color)
    row_left_squares(t, 12, pixel_size)
    t.left(180)
    row_left_squares(t, 2, pixel_size)
    t.forward(2 * pixel_size)
    row_left_squares(t, 6, pixel_size)
    t.right(90)
    t.forward(2 * pixel_size)
    t.left(90)
    t.forward(4 * pixel_size)
    t.left(180)
    row_right_squares(t, 14, pixel_size)
    t.left(180)
    row_right_squares(t, 15, pixel_size)
    double_right_linear_traverse(t, pixel_size)
    row_right_squares(t, 15, pixel_size)
    t.left(180)
    row_right_squares(t, 16, pixel_size)
    double_right_linear_traverse(t, pixel_size)
    row_right_squares(t, 16, pixel_size)
    t.left(180)
    row_right_squares(t, 16, pixel_size)
    double_right_linear_traverse(t, pixel_size)
    row_right_squares(t, 16, pixel_size)
    t.left(180)
    row_right_squares(t, 15, pixel_size)
    double_right_linear_traverse(t, pixel_size)
    row_right_squares(t, 15, pixel_size)
    t.backward(14 * pixel_size)
    row_left_squares(t, 14, pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    t.left(90)
    row_left_squares(t, 12, pixel_size)
    t.backward(12 * pixel_size)
    row_right_squares(t, 2, pixel_size)
    t.forward(2 * pixel_size)
    row_right_squares(t, 6, pixel_size)

    # Reflet
    t.backward(10 * pixel_size)
    walk_along_up_square_left(t, pixel_size)
    t.color("#FFFFFF")
    row_right_squares(t, 2, pixel_size)
    row_left_squares(t, 1, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    row_right_squares(t, 5, pixel_size)
    row_left_squares(t, 1, pixel_size)

    # Oeil
    t.up()
    long_left_diagonal_from_above(t, pixel_size)
    row_left_squares(t, 3, pixel_size)
    t.backward(2 * pixel_size)
    row_right_squares(t, 2, pixel_size)
    t.right(90)
    row_left_squares(t, 2, pixel_size)
    left_square(t, pixel_size)
    right_square(t, pixel_size)

    # Bras
    t.up()
    t.backward(9 * pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.down()
    row_left_squares(t, 2, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.right(90)
    t.forward(3 * pixel_size)
    t.left(180)
    row_left_squares(t, 4, pixel_size)
    t.backward(4 * pixel_size)
    row_right_squares(t, 4, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    row_left_squares(t, 3, pixel_size)
    t.backward(3 * pixel_size)
    row_right_squares(t, 4, pixel_size)
    double_right_linear_traverse(t, pixel_size)
    row_right_squares(t, 4, pixel_size)
    t.left(180)
    t.forward(pixel_size)
    row_right_squares(t, 2, pixel_size)
