import turtle
import time
import usefull

def billBalle(t, color):
    t.speed(100)

    # Corps
    t.color(color)
    usefull.row_left_squares(t, 12)
    t.left(180)
    usefull.row_left_squares(t, 2)
    t.forward(40)
    usefull.row_left_squares(t, 6)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(80)
    t.left(180)
    usefull.row_right_squares(t, 14)
    t.left(180)
    usefull.row_right_squares(t, 15)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 15)
    t.left(180)
    usefull.row_right_squares(t, 16)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 16)
    t.left(180)
    usefull.row_right_squares(t, 16)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 16)
    t.left(180)
    usefull.row_right_squares(t, 15)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 15)
    t.backward(280)
    usefull.row_left_squares(t, 14)
    t.left(90)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 12)
    t.backward(240)
    usefull.row_right_squares(t, 2)
    t.forward(40)
    usefull.row_right_squares(t, 6)

    # Reflet
    t.backward(200)
    t.left(90)
    t.forward(20)
    t.right(90)
    t.color("#FFFFFF")
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 1)
    t.up()
    t.forward(20)
    t.down()
    usefull.row_right_squares(t, 5)
    usefull.row_left_squares(t, 1)

    # Oeil
    t.up()
    usefull.long_left_diagonal_from_above(t)
    usefull.row_left_squares(t, 3)
    t.backward(40)
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_left_squares(t, 2)
    usefull.left_square(t)
    usefull.right_square(t)

    # Bras
    t.up()
    t.backward(180)
    t.left(90)
    t.forward(20)
    t.down()
    usefull.row_left_squares(t, 2)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.left(180)
    usefull.row_left_squares(t, 4)
    t.backward(80)
    usefull.row_right_squares(t, 4)
    t.right(90)
    t.forward(20)
    usefull.row_left_squares(t, 3)
    t.backward(60)
    usefull.row_right_squares(t, 4)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 4)
    t.left(180)
    t.forward(20)
    usefull.row_right_squares(t, 2)

    time.sleep(5)

t = turtle.Turtle()
billBalle(t, "#000000")