import usefull

def boo(t, body_color, mouth_color, pixel_size):
    t.speed(100)

    # Contour noir
    usefull.row_right_squares(t, 4, pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.double_walk_along_up_square_left(t, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    usefull.left_square(t, pixel_size)
    t.forward(pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)
    usefull.row_left_squares(t, 3, pixel_size)
    usefull.double_walk_along_up_square_left(t, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    usefull.left_square(t, pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.row_right_squares(t, 5, pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.row_right_squares(t, 5, pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)

    # Encrage du corps
    t.color(body_color)
    t.begin_fill()
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(4*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(3*pixel_size)
    usefull.walk_along_up_square_left(t, pixel_size)
    t.forward(3*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(5*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(5*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(3*pixel_size)
    t.end_fill()

    # Yeux
    t.up()
    t.color("black")
    t.left(90)
    t.forward(7*pixel_size)
    t.down()
    usefull.row_left_squares(t, 2, pixel_size)
    t.up()
    t.left(90)
    t.forward(2*pixel_size)
    t.left(90)
    t.down()
    usefull.row_right_squares(t, 2, pixel_size)

    # Main
    t.up()
    t.left(90)
    t.forward(5*pixel_size)
    t.down()
    usefull.right_square(t, pixel_size)
    t.forward(pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    t.right(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.right_square(t, pixel_size)

    # Bouche
    t.up()
    t.forward(pixel_size)
    t.right(90)
    t.forward(5*pixel_size)
    t.down()
    t.color(mouth_color)
    usefull.row_left_squares(t, 5, pixel_size)
    t.left(180)
    usefull.row_left_squares(t, 5, pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    usefull.left_square(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(180)
    usefull.row_right_squares(t, 5, pixel_size)
    t.left(90)
    usefull.left_square(t, pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(pixel_size)
    t.left(90)
    t.forward(3*pixel_size)
    usefull.right_square(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(2*pixel_size)
    usefull.right_square(t, pixel_size)