from usefull.usefull import *


def boo(t, type_color, pixel_size):
    t.speed(100)

    if type_color == 1:
        body_color = "#FFFFFF"
        mouth_color = "#FF0000"
    else:
        body_color = "#9932CC"
        mouth_color = "#191970"

    # Contour noir
    row_right_squares(t, 4, pixel_size)
    row_left_squares(t, 2, pixel_size)
    double_walk_along_up_square_left(t, pixel_size)
    row_right_squares(t, 2, pixel_size)
    left_square(t, pixel_size)
    t.forward(pixel_size)
    t.left(90)
    t.forward(pixel_size)
    row_right_squares(t, 3, pixel_size)
    row_left_squares(t, 3, pixel_size)
    double_walk_along_up_square_left(t, pixel_size)
    row_right_squares(t, 2, pixel_size)
    left_square(t, pixel_size)
    long_left_diagonal(t, pixel_size)
    t.left(90)
    row_left_squares(t, 2, pixel_size)
    row_right_squares(t, 5, pixel_size)
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    right_square(t, pixel_size)
    t.forward(pixel_size)
    t.right(90)
    t.forward(2 * pixel_size)
    t.left(90)
    row_left_squares(t, 2, pixel_size)
    row_right_squares(t, 5, pixel_size)
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    right_square(t, pixel_size)
    t.forward(pixel_size)
    walk_along_up_square_right(t, pixel_size)
    row_right_squares(t, 3, pixel_size)

    # Encrage du corps
    t.color(body_color)
    t.begin_fill()
    walk_along_up_square_right(t, pixel_size)
    t.forward(4 * pixel_size)
    long_left_diagonal(t, pixel_size)
    long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(3 * pixel_size)
    walk_along_up_square_left(t, pixel_size)
    t.forward(3 * pixel_size)
    long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(2 * pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(5 * pixel_size)
    long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(2 * pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(5 * pixel_size)
    long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(3 * pixel_size)
    t.end_fill()

    # Yeux
    t.up()
    t.color("black")
    t.left(90)
    t.forward(7 * pixel_size)
    t.down()
    row_left_squares(t, 2, pixel_size)
    t.up()
    t.left(90)
    t.forward(2 * pixel_size)
    t.left(90)
    t.down()
    row_right_squares(t, 2, pixel_size)

    # Main
    t.up()
    t.left(90)
    t.forward(5 * pixel_size)
    t.down()
    right_square(t, pixel_size)
    t.forward(pixel_size)
    row_left_squares(t, 2, pixel_size)
    t.right(90)
    row_left_squares(t, 2, pixel_size)
    right_square(t, pixel_size)

    # Bouche
    t.up()
    t.forward(pixel_size)
    t.right(90)
    t.forward(5 * pixel_size)
    t.down()
    t.color(mouth_color)
    row_left_squares(t, 5, pixel_size)
    t.left(180)
    row_left_squares(t, 5, pixel_size)
    t.right(90)
    t.forward(2 * pixel_size)
    left_square(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(180)
    row_right_squares(t, 5, pixel_size)
    t.left(90)
    left_square(t, pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    right_square(t, pixel_size)
    t.forward(pixel_size)
    t.left(90)
    t.forward(3 * pixel_size)
    right_square(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    right_square(t, pixel_size)
    t.forward(2 * pixel_size)
    right_square(t, pixel_size)
