import turtle
import time
import usefull

def carapace(t, main_color):
    t.speed(100)

    # Contour noir
    usefull.left_square(t)
    usefull.row_right_squares(t, 1)
    usefull.double_walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 1)
    usefull.double_walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 4)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 1)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.row_right_squares(t, 5)
    t.backward(20)
    usefull.row_left_squares(t, 3)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 1)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    t.backward(20)
    usefull.row_right_squares(t, 6)
    t.backward(20)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    usefull.row_left_squares(t, 1)
    usefull.row_right_squares(t, 2)
    usefull.double_walk_along_up_square(t)
    usefull.row_left_squares(t, 3)
    t.backward(20)
    usefull.row_right_squares(t, 3)
    t.left(90)
    usefull.row_left_squares(t, 2)
    t.backward(20)
    usefull.row_right_squares(t, 3)
    t.right(90)
    t.forward(20)
    usefull.row_right_squares(t, 1)
    t.left(90)
    usefull.row_right_squares(t, 6)
    t.left(90)
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 3)
    t.backward(20)
    usefull.row_left_squares(t, 2)

    # Bordure blanche
    t.color("#FFFFFF")
    t.right(90)
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 3)
    t.left(90)
    usefull.left_square(t)
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 4)
    t.backward(80)
    usefull.row_right_squares(t, 6)
    t.right(90)
    t.forward(20)
    usefull.right_square(t)
    usefull.row_left_squares(t, 2)
    t.left(90)
    usefull.row_left_squares(t, 3)
    t.right(90)
    usefull.row_right_squares(t, 1)

    # Encrage
    t.up()
    t.forward(40)
    t.right(90)
    t.color(main_color)
    t.down()
    t.begin_fill()
    t.forward(280)
    t.right(90)
    t.forward(20)
    t.right(90)
    usefull.long_left_diagonal_from_above(t)
    usefull.double_walk_along_up_square(t)
    t.forward(40)
    t.right(90)
    t.forward(120)
    usefull.double_walk_along_up_square(t)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.right(90)
    t.forward(20)
    t.begin_fill()
    for _ in range(2):
        t.forward(240)
        t.left(90)
        t.forward(60)
        t.left(90)
    t.end_fill()
    t.forward(20)
    t.left(90)
    t.forward(60)
    t.begin_fill()
    for _ in range(2):
        t.forward(40)
        t.right(90)
        t.forward(200)
        t.right(90)
    t.end_fill()
    t.forward(40)
    t.right(90)
    t.forward(20)
    usefull.row_left_squares(t, 8)
    t.left(180)
    t.forward(40)
    usefull.walk_along_up_square(t)
    usefull.row_right_squares(t, 4)

    # Craquelures
    t.left(180)
    t.color("#000000")
    usefull.row_right_squares(t, 4)
    t.right(90)
    t.forward(20)
    for _ in range(4):
        usefull.row_left_squares(t, 1)
        t.left(90)
        t.forward(20)
        t.right(90)
    t.up()
    t.right(90)
    t.forward(40)
    t.down()
    usefull.row_right_squares(t, 1)
    usefull.row_left_squares(t, 1)
    t.left(90)
    t.forward(40)
    usefull.left_square(t)
    t.right(90)
    usefull.row_right_squares(t, 4)
    usefull.left_square(t)
    t.right(90)
    t.forward(20)
    for _ in range(2):
        usefull.row_left_squares(t, 1)
        t.left(90)
        t.forward(20)
        t.right(90)
    t.left(90)
    usefull.long_left_diagonal_from_above(t)
    t.left(180)
    for _ in range(4):
        usefull.row_right_squares(t, 1)
        t.right(90)
        t.forward(20)
        t.left(90)

    time.sleep(5)

t = turtle.Turtle()
carapace(t, "#006600")