import usefull

def champignon(t, color):
    t.speed(100)

    # Contour noir
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.left_square(t)
    usefull.low_traverse(t)
    usefull.row_right_squares(t, 8)
    usefull.left_square(t)
    usefull.low_traverse(t)
    usefull.row_right_squares(t, 3)
    t.right(90)
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 6)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.right_square(t)
    usefull.double_high_traverse(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 7)
    t.backward(20)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.right_square(t)
    usefull.double_high_traverse(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 6)
    t.left(90)
    usefull.row_right_squares(t, 3)
    usefull.row_left_squares(t, 2)
    t.right(90)
    usefull.row_left_squares(t, 2)
    t.left(180)
    t.forward(40)
    t.right(90)
    usefull.row_left_squares(t, 3)
    t.right(90)
    usefull.row_left_squares(t, 2)
    t.left(180)
    t.forward(40)
    t.right(90)
    usefull.row_left_squares(t, 3)
    usefull.right_square(t)

    # Zone beige
    t.color("#FFC1A0")
    t.begin_fill()
    t.right(90)
    usefull.low_traverse(t)
    usefull.double_right_linear_traverse(t)
    usefull.low_traverse(t)
    t.right(90)
    t.forward(160)
    t.right(90)
    usefull.low_traverse(t)
    usefull.double_right_linear_traverse(t)
    usefull.low_traverse(t)
    usefull.double_right_linear_traverse(t)
    usefull.long_left_diagonal_from_above(t)
    t.left(90)
    t.forward(40)
    usefull.double_right_linear_traverse(t)
    usefull.long_left_diagonal_from_above(t)
    usefull.double_walk_along_up_square_left(t)
    t.forward(40)
    t.end_fill()

    # Zone colorée
    t.color(color)
    t.begin_fill()
    t.forward(60)
    t.left(90)
    t.forward(120)
    t.left(90)
    usefull.double_high_traverse(t)
    t.forward(20)
    usefull.walk_along_up_square_right(t)
    t.forward(40)
    usefull.walk_along_up_square_right(t)
    t.forward(120)
    t.left(90)
    usefull.double_high_traverse(t)
    t.forward(20)
    usefull.walk_along_up_square_right(t)
    t.forward(40)
    usefull.walk_along_up_square_right(t)
    t.forward(120)
    t.left(90)
    t.forward(60)
    usefull.walk_along_up_square_left(t)
    t.forward(160)
    t.right(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc inférieur droit
    t.left(180)
    t.forward(20)
    t.color("white")
    t.right(90)
    t.begin_fill()
    usefull.long_left_diagonal_from_above(t)
    usefull.walk_along_up_square_right(t)
    usefull.long_left_diagonal_from_above(t)
    usefull.walk_along_up_square_right(t)
    usefull.long_left_diagonal_from_above(t)
    usefull.walk_along_up_square_right(t)
    usefull.long_left_diagonal_from_above(t)
    t.right(90)
    t.forward(20)
    t.end_fill()

    # Pois blanc supérieur droit
    t.up()
    t.left(180)
    t.forward(100)
    t.right(90)
    t.down()
    t.begin_fill()
    t.forward(40)
    t.left(90)
    usefull.long_left_diagonal_from_above(t)
    usefull.walk_along_up_square_right(t)
    t.forward(40)
    usefull.walk_along_up_square_right(t)
    t.forward(40)
    t.left(90)
    usefull.long_left_diagonal_from_above(t)
    t.right(90)
    usefull.low_traverse(t)
    t.right(90)
    usefull.low_traverse(t)
    t.end_fill()

    # Pois blanc central
    t.up()
    t.left(180)
    t.forward(60)
    t.left(90)
    t.down()
    t.begin_fill()
    t.forward(60)
    t.right(90)
    usefull.low_traverse(t)
    usefull.from_above(t)
    usefull.low_traverse(t)
    usefull.from_above(t)
    usefull.low_traverse(t)
    usefull.from_above(t)
    usefull.low_traverse(t)
    t.end_fill()

    # Pois blanc supérieur gauche
    t.up()
    t.left(180)
    t.forward(120)
    t.down()
    t.begin_fill()
    t.forward(20)
    usefull.double_right_linear_traverse(t)
    usefull.low_traverse(t)
    usefull.double_right_linear_traverse(t)
    t.forward(20)
    t.right(90)
    usefull.low_traverse(t)
    t.right(90)
    usefull.low_traverse(t)
    t.end_fill()

    # Pois blanc inférieur gauche
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    t.forward(40)
    t.right(90)
    usefull.low_traverse(t)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(80)
    t.right(90)
    t.forward(20)
    t.right(90)
    usefull.low_traverse(t)
    t.end_fill()