from usefull.usefull import *


def cheep(t, type_color, pixel_size):
    t.speed(100)

    if type_color == 1:
        body_color = "#FF0000"
    else:
        body_color = "#00FF00"

    # Contour noir
    t.color("#000000")
    row_left_squares(t, 4, pixel_size)
    t.backward(pixel_size)
    row_right_squares(t, 6, pixel_size)
    row_left_squares(t, 2, pixel_size)
    double_walk_along_up_square_left(t, pixel_size)
    t.backward(pixel_size)
    row_right_squares(t, 2, pixel_size)
    row_left_squares(t, 3, pixel_size)
    double_walk_along_up_square_left(t, pixel_size)
    row_right_squares(t, 1, pixel_size)
    t.left(90)
    row_right_squares(t, 3, pixel_size)
    t.left(90)
    row_right_squares(t, 1, pixel_size)
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    row_left_squares(t, 3, pixel_size)
    t.right(90)
    row_left_squares(t, 1, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    left_square(t, pixel_size)
    right_square(t, pixel_size)
    t.left(90)
    row_left_squares(t, 4, pixel_size)
    t.right(90)
    for _ in range(4):
        right_square(t, pixel_size)
        t.forward(pixel_size)
        t.right(90)
        t.forward(pixel_size)
        t.left(90)
    t.right(90)
    row_left_squares(t, 3, pixel_size)
    right_square(t, pixel_size)
    t.backward(3 * pixel_size)
    t.left(90)
    row_right_squares(t, 4, pixel_size)
    row_left_squares(t, 1, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    walk_along_up_square_right(t, pixel_size)
    row_left_squares(t, 2, pixel_size)
    row_right_squares(t, 5, pixel_size)
    t.left(90)
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    row_left_squares(t, 2, pixel_size)
    t.backward(pixel_size)
    row_right_squares(t, 5, pixel_size)
    walk_along_up_square_right(t, pixel_size)
    for _ in range(2):
        right_square(t, pixel_size)
        t.forward(pixel_size)
        t.right(90)
        t.forward(pixel_size)
        t.left(90)
    t.up()
    t.backward(6 * pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    t.left(180)
    t.down()
    row_left_squares(t, 5, pixel_size)
    row_right_squares(t, 1, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    row_left_squares(t, 3, pixel_size)
    t.backward(pixel_size)
    row_right_squares(t, 5, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    row_left_squares(t, 4, pixel_size)
    row_right_squares(t, 1, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    row_left_squares(t, 3, pixel_size)
    walk_along_up_square_left(t, pixel_size)
    row_left_squares(t, 2, pixel_size)
    t.left(180)
    t.forward(3 * pixel_size)
    walk_along_up_square_left(t, pixel_size)
    row_left_squares(t, 1, pixel_size)
    t.up()
    t.forward(2 * pixel_size)
    t.left(90)
    t.forward(6 * pixel_size)
    t.down()
    row_left_squares(t, 3, pixel_size)
    t.left(90)
    row_left_squares(t, 4, pixel_size)
    right_square(t, pixel_size)
    t.backward(3 * pixel_size)
    t.right(90)
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(5 * pixel_size)
    row_left_squares(t, 1, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    row_right_squares(t, 2, pixel_size)
    left_square(t, pixel_size)

    # Bouche
    t.left(90)
    t.color("#FFFF00")
    row_left_squares(t, 3, pixel_size)
    walk_along_up_square_right(t, pixel_size)
    row_right_squares(t, 3, pixel_size)
    t.left(180)
    row_right_squares(t, 5, pixel_size)
    t.right(90)
    t.forward(2 * pixel_size)
    left_square(t, pixel_size)
    right_square(t, pixel_size)
    t.forward(pixel_size)
    t.right(90)
    row_left_squares(t, 4, pixel_size)
    t.left(180)
    row_left_squares(t, 2, pixel_size)

    # Ventre
    walk_along_up_square_right(t, pixel_size)
    t.color("#FFFFFF")
    t.up()
    t.forward(2 * pixel_size)
    t.down()
    row_right_squares(t, 5, pixel_size)
    t.backward(4 * pixel_size)
    row_left_squares(t, 5, pixel_size)
    t.backward(4 * pixel_size)
    double_walk_along_up_square_left(t, pixel_size)
    row_right_squares(t, 6, pixel_size)
    t.backward(5 * pixel_size)
    row_left_squares(t, 5, pixel_size)

    # Queue
    t.up()
    t.forward(pixel_size)
    t.color("#FFFF00")
    t.down()
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    row_left_squares(t, 3, pixel_size)
    t.backward(2 * pixel_size)
    row_right_squares(t, 3, pixel_size)

    # Aile
    t.color("#FFFFFF")
    t.forward(pixel_size)
    t.left(90)
    row_left_squares(t, 4, pixel_size)
    t.backward(4 * pixel_size)
    row_right_squares(t, 3, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    row_left_squares(t, 1, pixel_size)
    t.right(90)
    row_right_squares(t, 2, pixel_size)
    t.backward(pixel_size)
    row_left_squares(t, 2, pixel_size)

    # Corps
    t.color(body_color)
    row_right_squares(t, 3, pixel_size)
    t.backward(2 * pixel_size)
    row_left_squares(t, 3, pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    t.left(90)
    row_left_squares(t, 1, pixel_size)
    right_square(t, pixel_size)
    row_left_squares(t, 2, pixel_size)
    t.up()
    t.forward(4 * pixel_size)
    t.down()
    left_square(t, pixel_size)
    t.up()
    t.left(90)
    t.forward(4 * pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.down()
    row_right_squares(t, 4, pixel_size)
    t.backward(3 * pixel_size)
    row_left_squares(t, 3, pixel_size)
    double_right_linear_traverse(t, pixel_size)
    row_right_squares(t, 5, pixel_size)
    t.left(180)
    t.forward(pixel_size)
    row_right_squares(t, 4, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.right(90)
    row_left_squares(t, 3, pixel_size)

    # Crête
    t.forward(pixel_size)
    t.left(90)
    t.color("#FFFF00")
    row_right_squares(t, 2, pixel_size)
    t.left(90)
    left_square(t, pixel_size)
    row_right_squares(t, 5, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    left_square(t, pixel_size)
    t.right(90)
    row_left_squares(t, 3, pixel_size)

    # Yeux
    t.up()
    t.color("#FFFFFF")
    double_right_linear_traverse(t, pixel_size)
    t.forward(3 * pixel_size)
    t.left(90)
    t.down()
    t.begin_fill()
    t.forward(5 * pixel_size)
    t.right(90)
    low_traverse(t, pixel_size)
    t.right(90)
    t.forward(2 * pixel_size)
    walk_along_up_square_right(t, pixel_size)
    t.forward(5 * pixel_size)
    t.right(90)
    t.forward(4 * pixel_size)
    t.right(90)
    low_traverse(t, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.right(90)
    low_traverse(t, pixel_size)
    walk_along_up_square_left(t, pixel_size)
    low_traverse(t, pixel_size)
    from_above(t, pixel_size)
    low_traverse(t, pixel_size)
    t.end_fill()

    # Pupilles
    t.left(180)
    t.forward(4 * pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    t.color("#000000")
    row_left_squares(t, 2, pixel_size)
    t.up()
    double_right_linear_traverse(t, pixel_size)
    t.down()
    row_left_squares(t, 2, pixel_size)
