import usefull

def etoile(t, color, pixel_size):
    t.speed(100)

    # Contour noir
    usefull.row_right_squares(t, 3, pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.double_walk_along_up_square_left(t, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    usefull.row_left_squares(t, 1, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)
    t.backward(pixel_size)
    t.left(90)
    usefull.row_right_squares(t, 1, pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.double_walk_along_up_square_left(t, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    usefull.row_left_squares(t, 1, pixel_size)
    usefull.row_right_squares(t, 1, pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 1, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 4, pixel_size)
    t.forward(pixel_size)
    t.right(90)
    usefull.row_right_squares(t, 2, pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.row_right_squares(t ,2, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    usefull.row_left_squares(t, 5, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    for _ in range(4):
        usefull.left_square(t, pixel_size)
        t.forward(pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
    t.right(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    usefull.left_square(t, pixel_size)

    # Encrage
    t.color(color)
    t.left(90)
    t.begin_fill()
    t.forward(pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    usefull.walk_along_up_square_left(t, pixel_size)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    usefull.walk_along_up_square_left(t, pixel_size)
    t.forward(pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.left(90)
    t.forward(4*pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    usefull.long_left_diagonal(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    t.forward(4*pixel_size)
    t.left(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    t.forward(2*pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.end_fill()

    # Yeux
    t.up()
    t.left(180)
    t.forward(6*pixel_size)
    t.left(90)
    t.forward(5*pixel_size)
    t.color("#000000")
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)
    t.up()
    t.right(90)
    t.forward(pixel_size)
    t.right(90)
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)