import turtle
import time
import usefull

def etoile(t, color):
    t.speed(100)

    # Contour noir
    usefull.row_right_squares(t, 3)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 1)
    usefull.row_right_squares(t, 2)
    t.right(90)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 3)
    t.backward(20)
    t.left(90)
    usefull.row_right_squares(t, 1)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 1)
    usefull.row_right_squares(t, 1)
    t.right(90)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 1)
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_left_squares(t, 4)
    t.forward(20)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.right_square(t)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t ,2)
    t.right(90)
    t.forward(20)
    usefull.row_left_squares(t, 5)
    t.left(90)
    t.forward(20)
    for _ in range(4):
        usefull.left_square(t)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.right(90)
    t.right(90)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 2)
    t.right(90)
    t.forward(20)
    usefull.left_square(t)

    time.sleep(5)

t = turtle.Turtle()
etoile(t, "#000005")