import usefull

def goomba(t, body_color):
    t.speed(100)

    # Pieds
    usefull.row_left_squares(t, 2)
    t.backward(60)
    usefull.row_right_squares(t, 5)
    t.backward(100)
    t.right(90)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 6)
    t.backward(100)
    usefull.row_right_squares(t, 5)
    t.up()
    t.forward(40)
    t.down()
    usefull.row_right_squares(t, 3)
    t.backward(40)
    usefull.row_left_squares(t, 2)
    t.left(90)
    usefull.right_square(t)
    t.forward(20)
    usefull.left_square(t)
    usefull.right_square(t)

    # Corps
    t.left(90)
    t.forward(20)
    t.color("#FFC992")
    usefull.row_right_squares(t, 5)
    t.backward(80)
    usefull.row_left_squares(t, 3)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(60)
    t.left(180)
    usefull.row_right_squares(t, 8)
    t.backward(160)
    usefull.row_left_squares(t, 8)
    t.left(90)
    usefull.low_traverse(t)
    usefull.row_right_squares(t, 6)

    # Corps
    t.up()
    t.forward(100)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.color(body_color)
    t.down()
    usefull.row_left_squares(t, 16)
    t.left(180)
    t.forward(20)
    usefull.row_left_squares(t, 4)
    t.forward(120)
    usefull.row_left_squares(t, 4)
    t.forward(20)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 16)
    t.backward(320)
    usefull.row_left_squares(t, 16)
    t.up()
    t.left(90)
    usefull.long_left_diagonal_from_above(t)
    t.down()
    usefull.row_right_squares(t, 14)
    t.backward(280)
    usefull.row_left_squares(t, 14)
    t.up()
    usefull.double_right_linear_traverse(t)
    t.forward(20)
    usefull.row_right_squares(t, 12)
    t.backward(220)
    usefull.row_left_squares(t, 10)
    t.up()
    t.left(90)
    usefull.long_left_diagonal_from_above(t)
    t.down()
    usefull.row_left_squares(t, 8)
    t.backward(140)
    usefull.row_right_squares(t, 6)
    t.backward(100)
    usefull.walk_along_up_square(t)
    usefull.row_right_squares(t, 4)

    # Yeux
    t.left(90)
    t.forward(120)
    t.color("#FFFFFF")
    usefull.row_left_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 4)
    t.up()
    t.right(90)
    t.forward(140)
    t.right(90)
    t.down()
    usefull.row_left_squares(t, 4)
    t.right(90)
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 2)

    # Sourcils + pupilles
    t.up()
    t.forward(40)
    t.right(90)
    t.forward(80)
    t.left(180)
    t.color("#000000")
    t.down()
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 2)
    usefull.right_square(t)
    t.right(90)
    usefull.row_right_squares(t, 5)
    usefull.left_square(t)
    t.right(90)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.row_right_squares(t, 2)