import usefull

def mario_luigi(t, clothes_color, pixel_size):
    t.speed(100)

    # Chaussures
    t.color("#663300")
    usefull.row_right_squares(t, 4, pixel_size)
    t.backward(3*pixel_size)
    usefull.row_left_squares(t, 3, pixel_size)
    t.up()
    t.forward(4*pixel_size)
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)
    t.backward(3*pixel_size)
    usefull.row_right_squares(t, 4, pixel_size)

    # Salopette
    t.up()
    t.left(90)
    t.forward(2*pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.color("#000077")
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)
    t.forward(2*pixel_size)
    usefull.row_left_squares(t, 3, pixel_size)
    t.left(180)
    usefull.row_left_squares(t, 8, pixel_size)
    t.left(90)
    usefull.low_traverse(t, pixel_size)
    usefull.row_right_squares(t, 6, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.right(90)
    usefull.row_left_squares(t, 1, pixel_size)
    t.forward(pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    t.forward(pixel_size)
    usefull.left_square(t, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(90)
    usefull.row_right_squares(t, 4, pixel_size)
    t.right(90)
    usefull.row_right_squares(t, 3, pixel_size)
    t.backward(2*pixel_size)
    t.right(90)
    t.forward(3*pixel_size)
    usefull.left_square(t, pixel_size)

    # Boutons
    t.up()
    t.right(90)
    t.forward(pixel_size)
    t.color("#FFFF00")
    t.down()
    usefull.left_square(t, pixel_size)
    t.up()
    t.right(90)
    t.forward(2*pixel_size)
    t.down()
    usefull.left_square(t, pixel_size)

    # Mains
    t.up()
    t.forward(3*pixel_size)
    t.color("#FFA07A")
    t.down()
    usefull.row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_right_squares(t, 2, pixel_size)
    t.backward(2*pixel_size)
    usefull.row_left_squares(t, 3, pixel_size)
    t.up()
    t.forward(6*pixel_size)
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)
    t.backward(2*pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)

    # T-shirt
    t.color(clothes_color)
    usefull.left_square(t, pixel_size)
    t.backward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    usefull.row_left_squares(t, 4, pixel_size)
    t.backward(3*pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    usefull.row_right_squares(t, 2, pixel_size)
    t.up()
    usefull.low_traverse(t, pixel_size)
    t.right(90)
    t.down()
    usefull.row_right_squares(t, 1, pixel_size)
    usefull.left_square(t, pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)
    t.backward(4*pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 3, pixel_size)
    t.backward(3*pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.left(180)
    t.up()
    t.forward(3*pixel_size)
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)

    # Visage
    t.up()
    t.forward(2*pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.left(90)
    t.color("#FFA07A")
    t.down()
    usefull.row_left_squares(t, 7, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    usefull.row_left_squares(t, 2, pixel_size)
    t.backward(2*pixel_size)
    t.right(90)
    usefull.row_right_squares(t, 4, pixel_size)
    t.backward(2*pixel_size)
    usefull.row_left_squares(t, 3, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    usefull.row_left_squares(t, 3, pixel_size)
    t.up()
    t.left(90)
    usefull.long_left_diagonal_from_above(t, pixel_size)
    t.down()
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.left_square(t, pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(pixel_size)
    ### Yeux ###
    t.color("#000000")
    usefull.left_square(t, pixel_size)
    usefull.right_square(t, pixel_size)
    t.forward(pixel_size)
    ### End ###
    t.color("#FFA07A")
    usefull.row_left_squares(t, 3, pixel_size)
    t.backward(3*pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)

    # Pilosité
    t.color("#663300")
    usefull.row_right_squares(t, 3, pixel_size)
    t.left(90)
    usefull.row_right_squares(t, 3, pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 1, pixel_size)
    t.up()
    t.forward(4*pixel_size)
    t.down()
    usefull.row_left_squares(t, 4, pixel_size)
    t.backward(3*pixel_size)
    t.left(90)
    usefull.row_right_squares(t, 2, pixel_size)
    t.up()
    t.left(90)
    t.forward(3*pixel_size)
    t.down()
    usefull.row_left_squares(t, 2, pixel_size)
    t.right(90)
    usefull.row_right_squares(t, 2, pixel_size)

    # Casquette
    t.color(clothes_color)
    usefull.row_left_squares(t, 1, pixel_size)
    t.right(90)
    usefull.row_left_squares(t, 5, pixel_size)
    t.backward(5*pixel_size)
    usefull.row_right_squares(t, 8, pixel_size)