import usefull

def oeuf(t, egg_color, dots_color):
    t.speed(100)

    # Contour noir
    usefull.row_right_squares(t, 4)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.right_square(t)
    usefull.double_high_traverse(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 4)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.left_square(t)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.right_square(t)
    t.forward(20)
    t.left(90)
    usefull.row_right_squares(t, 4)
    usefull.left_square(t)
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.right_square(t)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 2)
    usefull.walk_along_up_square(t)
    usefull.row_right_squares(t, 4)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.right_square(t)
    t.forward(20)
    usefull.walk_along_up_square(t)
    usefull.row_right_squares(t, 2)

    # Encrage
    t.color(egg_color)
    t.begin_fill()
    usefull.walk_along_up_square(t)
    t.forward(80)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(80)
    usefull.long_left_diagonal(t)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    t.right(90)
    usefull.low_traverse(t)
    usefull.walk_along_up_square(t)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.right(90)
    usefull.low_traverse(t)
    usefull.walk_along_up_square(t)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(80)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    t.forward(40)
    t.end_fill()

    # Pois inférieur gauche
    t.up()
    t.color(dots_color)
    t.backward(40)
    t.left(90)
    t.down()
    usefull.row_right_squares(t, 3)
    t.left(90)
    usefull.row_right_squares(t, 2)
    t.backward(20)
    t.left(90)
    usefull.row_left_squares(t, 2)

    # Pois inférieur droit
    t.up()
    t.left(90)
    t.forward(180)
    t.left(90)
    t.down()
    usefull.row_left_squares(t, 3)
    t.backward(60)
    usefull.row_right_squares(t, 4)
    t.right(90)
    t.forward(20)
    t.right(90)
    usefull.row_left_squares(t, 2)

    # Pois supérieur droit
    t.up()
    t.left(180)
    t.forward(80)
    t.down()
    usefull.row_left_squares(t, 2)
    t.backward(40)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 4)
    t.left(180)
    usefull.row_right_squares(t, 3)

    # Pois supérieur gauche
    t.up()
    t.right(90)
    t.forward(100)
    t.down()
    usefull.row_right_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 3)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.left(180)
    usefull.row_right_squares(t, 4)
    t.left(180)
    t.forward(20)
    usefull.row_right_squares(t, 3)

    # Pois central
    t.up()
    t.left(180)
    t.forward(120)
    t.down()
    usefull.row_right_squares(t, 3)
    usefull.low_traverse(t)
    t.left(90)
    usefull.row_left_squares(t, 5)
    t.backward(100)
    usefull.row_right_squares(t, 5)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 5)
    t.backward(80)
    usefull.row_left_squares(t, 3)