import usefull

def omb(t, body_color, pixel_size):
    t.speed(100)

    # Pieds
    t.color("#FFAA00")
    usefull.row_left_squares(t, 2, pixel_size)
    t.backward(2*pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)
    t.backward(2*pixel_size)
    usefull.walk_along_up_square_right(t, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.up()
    t.forward(4*pixel_size)
    t.down()
    usefull.row_right_squares(t, 2, pixel_size)
    t.backward(2*pixel_size)
    usefull.row_left_squares(t, 3, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(90)
    usefull.row_right_squares(t, 2, pixel_size)

    # Corps
    t.forward(pixel_size)
    t.color(body_color)
    usefull.row_left_squares(t, 4, pixel_size)
    t.forward(pixel_size)
    t.left(180)
    usefull.row_left_squares(t, 6, pixel_size)
    usefull.double_walk_along_up_square_left(t, pixel_size)
    t.forward(2*pixel_size)
    t.left(180)
    usefull.row_left_squares(t, 10, pixel_size)
    t.forward(pixel_size)
    t.left(180)
    usefull.row_left_squares(t, 12, pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 12, pixel_size)
    t.backward(12*pixel_size)
    usefull.row_right_squares(t, 13, pixel_size)
    usefull.double_right_linear_traverse(t, pixel_size)
    usefull.row_right_squares(t, 13, pixel_size)
    t.left(180)
    usefull.row_right_squares(t, 6, pixel_size)
    t.forward(pixel_size)
    usefull.row_right_squares(t, 1, pixel_size)
    t.forward(pixel_size)
    usefull.row_right_squares(t, 4, pixel_size)
    usefull.double_right_linear_traverse(t, pixel_size)
    usefull.row_right_squares(t, 4, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    usefull.row_right_squares(t, 1, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    usefull.row_right_squares(t, 6, pixel_size)
    t.left(180)
    usefull.row_right_squares(t, 6, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    usefull.row_right_squares(t, 1, pixel_size)
    t.up()
    t.forward(pixel_size)
    t.down()
    usefull.row_right_squares(t, 3, pixel_size)
    usefull.double_right_linear_traverse(t, pixel_size)
    usefull.row_right_squares(t, 12, pixel_size)
    t.backward(11*pixel_size)
    usefull.row_left_squares(t, 10, pixel_size)
    t.up()
    t.left(90)
    usefull.long_left_diagonal_from_above(t, pixel_size)
    t.down()
    usefull.row_left_squares(t, 8, pixel_size)
    t.backward(6*pixel_size)
    usefull.row_right_squares(t, 4, pixel_size)

    # Yeux
    t.left(90)
    t.forward(3*pixel_size)
    t.color("#FFFFFF")
    usefull.row_right_squares(t, 3, pixel_size)
    t.up()
    t.left(90)
    t.forward(pixel_size)
    t.left(90)
    t.down()
    usefull.row_right_squares(t, 3, pixel_size)

    # Clé
    t.up()
    t.right(90)
    t.forward(8*pixel_size)
    t.right(90)
    t.down()
    usefull.row_left_squares(t, 6, pixel_size)
    t.left(180)
    t.color("#000000")
    usefull.row_left_squares(t, 2, pixel_size)
    t.color("#FFFFFF")
    usefull.row_left_squares(t, 2, pixel_size)
    t.color("#000000")
    usefull.row_left_squares(t, 2, pixel_size)
    t.right(90)
    usefull.row_left_squares(t, 2, pixel_size)
    t.right(90)
    usefull.row_right_squares(t, 6, pixel_size)
    t.right(90)
    usefull.row_left_squares(t, 2, pixel_size)