import time
import turtle
import usefull

def omb(t, body_color):
    t.speed(100)

    # Pieds
    t.color("#FFAA00")
    usefull.row_left_squares(t, 2)
    t.backward(40)
    usefull.row_right_squares(t, 3)
    t.backward(40)
    usefull.walk_along_up_square_right(t)
    usefull.row_right_squares(t, 2)
    t.up()
    t.forward(80)
    t.down()
    usefull.row_right_squares(t, 2)
    t.backward(40)
    usefull.row_left_squares(t, 3)
    t.left(90)
    t.forward(20)
    t.left(90)
    usefull.row_right_squares(t, 2)

    # Corps
    t.forward(20)
    t.color(body_color)
    usefull.row_left_squares(t, 4)
    t.forward(20)
    t.left(180)
    usefull.row_left_squares(t, 6)
    usefull.double_walk_along_up_square_left(t)
    t.forward(40)
    t.left(180)
    usefull.row_left_squares(t, 10)
    t.forward(20)
    t.left(180)
    usefull.row_left_squares(t, 12)
    t.left(90)
    t.forward(40)
    t.left(90)
    usefull.row_left_squares(t, 12)
    t.backward(240)
    usefull.row_right_squares(t, 13)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 13)
    t.left(180)
    usefull.row_right_squares(t, 6)
    t.forward(20)
    usefull.row_right_squares(t, 1)
    t.forward(20)
    usefull.row_right_squares(t, 4)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 4)
    t.up()
    t.forward(20)
    t.down()
    usefull.row_right_squares(t, 1)
    t.up()
    t.forward(20)
    t.down()
    usefull.row_right_squares(t, 6)
    t.left(180)
    usefull.row_right_squares(t, 6)
    t.up()
    t.forward(20)
    t.down()
    usefull.row_right_squares(t, 1)
    t.up()
    t.forward(20)
    t.down()
    usefull.row_right_squares(t, 3)
    usefull.double_right_linear_traverse(t)
    usefull.row_right_squares(t, 12)
    t.backward(220)
    usefull.row_left_squares(t, 10)
    t.up()
    t.left(90)
    usefull.long_left_diagonal_from_above(t)
    t.down()
    usefull.row_left_squares(t, 8)
    t.backward(120)
    usefull.row_right_squares(t, 4)

    # Yeux
    t.left(90)
    t.forward(60)
    t.color("#FFFFFF")
    usefull.row_right_squares(t, 3)
    t.up()
    t.left(90)
    t.forward(20)
    t.left(90)
    t.down()
    usefull.row_right_squares(t, 3)

    # Clé
    t.up()
    t.right(90)
    t.forward(160)
    t.right(90)
    t.down()
    usefull.row_left_squares(t, 6)
    t.left(180)
    t.color("#000000")
    usefull.row_left_squares(t, 2)
    t.color("#FFFFFF")
    usefull.row_left_squares(t, 2)
    t.color("#000000")
    usefull.row_left_squares(t, 2)
    t.right(90)
    usefull.row_left_squares(t, 2)
    t.right(90)
    usefull.row_right_squares(t, 6)
    t.right(90)
    usefull.row_left_squares(t, 2)





    time.sleep(5)

t = turtle.Turtle()
omb(t, "#000000")