import usefull

def piece(t, color):
    t.speed(100)

    # Contour noir
    usefull.row_right_squares(t, 4)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 8)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 4)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 8)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    usefull.row_right_squares(t, 2)

    # Encrage
    t.color(color)
    t.begin_fill()
    usefull.walk_along_up_square(t)
    t.forward(80)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(160)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(80)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(160)
    usefull.long_left_diagonal(t)
    t.left(90)
    t.forward(40)
    t.end_fill()

    # Coeur
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(20)
    t.color("#000000")
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 8)
    t.left(90)
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 8)