import usefull

def pow(t, main_color, border_color):
    t.speed(100)

    # Fond
    t.begin_fill()
    for _ in range (4):
        t.forward(360)
        t.left(90)
    t.end_fill()

    # Bordure
    t.left(90)
    t.forward(80)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.color(border_color)
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 14)
    t.left(90)
    usefull.row_right_squares(t, 2)
    t.up()
    t.forward(200)
    t.down()
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 14)
    t.left(90)
    usefull.row_right_squares(t, 2)

    # Bleu principal
    t.left(90)
    t.color(main_color)
    t.begin_fill()
    for _ in range(2):
        t.forward(280)
        t.left(90)
        t.forward(40)
        t.left(90)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(240)
    t.left(90)
    t.down()
    t.begin_fill()
    for _ in range(2):
        t.forward(280)
        t.left(90)
        t.forward(40)
        t.left(90)
    t.end_fill()

    # P
    t.up()
    t.color("#FFFFFF")
    t.left(90)
    t.forward(60)
    t.down()
    usefull.row_left_squares(t, 8)
    t.backward(160)
    usefull.row_right_squares(t, 8)
    t.backward(20)
    t.right(90)
    t.forward(20)
    usefull.row_left_squares(t, 2)
    t.right(90)
    usefull.row_left_squares(t, 4)
    t.right(90)
    usefull.row_left_squares(t, 2)

    # O
    t.up()
    t.left(180)
    t.forward(100)
    t.left(90)
    t.backward(40)
    usefull.row_left_squares(t, 6)
    t.backward(140)
    usefull.row_right_squares(t, 8)
    t.backward(20)
    t.right(90)
    usefull.row_left_squares(t, 2)
    t.right(90)
    usefull.row_left_squares(t, 6)
    t.right(90)
    usefull.row_left_squares(t, 2)

    # W
    t.up()
    t.left(180)
    t.forward(80)
    t.down()
    usefull.row_right_squares(t, 2)
    t.forward(20)
    usefull.row_right_squares(t, 2)
    t.left(180)
    usefull.row_right_squares(t, 5)
    t.right(90)
    usefull.row_right_squares(t, 7)
    t.up()
    t.right(90)
    t.forward(60)
    t.right(90)
    t.down()
    usefull.row_right_squares(t, 6)
    t.left(90)
    t.forward(20)
    t.left(90)
    usefull.row_right_squares(t, 6)