import usefull

def tanuki(t, main_color, veins_color):
    t.speed(100)

    # Contour noir
    usefull.row_left_squares(t, 3)
    usefull.row_right_squares(t, 5)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    for _ in range(2):
        usefull.row_right_squares(t, 1)
        t.right(90)
        t.forward(20)
        t.left(90)
    usefull.walk_along_up_square(t)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 3)
    usefull.row_left_squares(t, 2)
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 1)
    t.left(90)
    usefull.row_right_squares(t, 2)
    t.right(90)
    t.forward(20)
    usefull.row_left_squares(t, 4)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 2)
    t.left(90)
    t.forward(20)
    for _ in range(3):
        usefull.row_right_squares(t, 1)
        t.right(90)
        t.forward(20)
        t.left(90)
    usefull.left_square(t)
    usefull.right_square(t)
    usefull.walk_along_up_square(t)
    usefull.row_right_squares(t, 2)
    t.left(90)
    usefull.row_right_squares(t, 2)

    # Encrage
    t.color(main_color)
    t.begin_fill()
    usefull.walk_along_up_square(t)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(100)
    usefull.long_left_diagonal(t)
    for _ in range(2):
        t.left(90)
        t.forward(20)
        t.right(90)
        t.forward(20)
    t.left(90)
    t.forward(40)
    usefull.walk_along_up_square(t)
    t.forward(60)
    usefull.long_left_diagonal(t)
    t.left(90)
    usefull.low_traverse(t)
    t.right(90)
    t.forward(80)
    
    for _ in range(2):
        t.left(90)
        t.forward(20)
        t.right(90)
        t.forward(40)
    for _ in range(2):
        t.left(90)
        t.forward(20)
        t.right(90)
        t.forward(20)
    t.left(90)
    t.forward(40)
    t.right(90)
    usefull.long_left_diagonal_from_above(t)
    t.left(90)
    t.forward(40)
    t.end_fill()

    # Veines
    t.left(90)
    t.forward(60)
    t.right(90)
    t.color(veins_color)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 1)
    t.right(90)
    t.forward(40)
    usefull.right_square(t)
    t.left(180)
    usefull.row_right_squares(t, 3)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 2)
    t.right(90)
    t.forward(40)
    usefull.right_square(t)
    t.left(180)
    usefull.row_right_squares(t, 4)
    t.right(90)
    usefull.row_right_squares(t, 2)
    usefull.row_left_squares(t, 2)

    # Queue
    t.up()
    t.left(90)
    t.forward(40)
    t.color(main_color)
    t.down()
    usefull.row_right_squares(t, 2)