from turtle import *
import usefull
import turtle
import time

def colline(t, pixel_size):
    tracer(5)
    t.up()
    t.backward(25*pixel_size)
    t.down()

    # Contour noir
    for i in range(3):
        usefull.row_left_squares(t, 1, pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
        for _ in range(3-i):
            usefull.row_left_squares(t, 2, pixel_size)
            t.left(90)
            t.forward(pixel_size)
            usefull.row_right_squares(t, 2, pixel_size)
            t.right(90)
            t.forward(pixel_size)

    usefull.row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.right(90)
    usefull.row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.right(90)
    usefull.row_right_squares(t, 3, pixel_size)
    usefull.row_left_squares(t, 5, pixel_size)
    usefull.row_right_squares(t, 3, pixel_size)
    t.right(90)
    t.forward(2*pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 2, pixel_size)
    usefull.row_right_squares(t, 2, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.left(90)
    for i in range(3):
        for _ in range(i+1):
            t.right(90)
            usefull.row_left_squares(t, 2, pixel_size)
            t.left(90)
            t.forward(pixel_size)
            usefull.row_right_squares(t, 2, pixel_size)
            t.right(90)
            t.forward(pixel_size)
            t.left(90)
        usefull.row_right_squares(t, 1, pixel_size)
        t.right(90)
        t.forward(pixel_size)
        t.left(90)

    # Remplissage vert
    t.left(180)
    t.forward(pixel_size)
    t.color("#00DD00")
    t.begin_fill()
    t.forward(60*pixel_size)
    t.right(180)
    t.begin_fill()
    for i in range(3):
        t.forward(pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
        for _ in range(3-i):
            t.forward(2*pixel_size)
            t.left(90)
            t.forward(pixel_size)
            t.right(90)
            t.forward(pixel_size)
            t.left(90)
            t.forward(2*pixel_size)
            t.right(90)
    for _ in range(2):
        t.forward(2*pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
    t.forward(3*pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.right(90)
    t.forward(5*pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.left(90)
    t.forward(3*pixel_size)
    for _ in range(2):
        t.right(90)
        t.forward(pixel_size)
        t.left(90)
        t.forward(2*pixel_size)
    for i in range(3):
        for _ in range(i+1):
            t.right(90)
            t.forward(2*pixel_size)
            t.left(90)
            t.forward(pixel_size)
            t.right(90)
            t.forward(pixel_size)
            t.left(90)
            t.forward(2*pixel_size)
        t.right(90)
        t.forward(pixel_size)
        t.left(90)
        t.forward(pixel_size)
    t.end_fill()

    # Trous noirs

    t.backward(32*pixel_size)
    t.left(90)
    t.forward(10*pixel_size)
    t.color("#000000")
    usefull.row_right_squares(t, 1, 3*pixel_size)
    usefull.row_right_squares(t, 1, 3*pixel_size)
    t.up()
    t.right(90)
    t.forward(7*pixel_size)
    t.left(90)
    t.forward(2*pixel_size)
    t.left(180)
    t.down()
    usefull.row_right_squares(t, 7, pixel_size)
    t.forward(pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(90)
    usefull.row_left_squares(t, 9, pixel_size)
    t.backward(pixel_size)
    t.left(180)
    usefull.row_left_squares(t, 7, pixel_size)
        

    time.sleep(5)

t = turtle.Turtle()
colline(t, 10)