from usefull.usefull import *


def colline(t, pixel_size):
    t.speed(100)

    t.up()
    t.backward(25 * pixel_size)
    t.down()

    # Contour noir
    t.color("black")
    for i in range(3):
        row_left_squares(t, 1, pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
        for _ in range(3 - i):
            row_left_squares(t, 2, pixel_size)
            t.left(90)
            t.forward(pixel_size)
            row_right_squares(t, 2, pixel_size)
            t.right(90)
            t.forward(pixel_size)

    row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.right(90)
    row_left_squares(t, 2, pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    t.right(90)
    row_right_squares(t, 3, pixel_size)
    row_left_squares(t, 5, pixel_size)
    row_right_squares(t, 3, pixel_size)
    t.right(90)
    t.forward(2 * pixel_size)
    t.left(90)
    row_left_squares(t, 2, pixel_size)
    row_right_squares(t, 2, pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.left(90)
    for i in range(3):
        for _ in range(i + 1):
            t.right(90)
            row_left_squares(t, 2, pixel_size)
            t.left(90)
            t.forward(pixel_size)
            row_right_squares(t, 2, pixel_size)
            t.right(90)
            t.forward(pixel_size)
            t.left(90)
        row_right_squares(t, 1, pixel_size)
        t.right(90)
        t.forward(pixel_size)
        t.left(90)

    # Remplissage vert
    t.left(180)
    t.forward(pixel_size)
    t.color("#0CC404")
    t.begin_fill()
    t.forward(60 * pixel_size)
    t.right(180)
    t.begin_fill()
    for i in range(3):
        t.forward(pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
        for _ in range(3 - i):
            t.forward(2 * pixel_size)
            t.left(90)
            t.forward(pixel_size)
            t.right(90)
            t.forward(pixel_size)
            t.left(90)
            t.forward(2 * pixel_size)
            t.right(90)
    for _ in range(2):
        t.forward(2 * pixel_size)
        t.left(90)
        t.forward(pixel_size)
        t.right(90)
    t.forward(3 * pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.right(90)
    t.forward(5 * pixel_size)
    t.right(90)
    t.forward(pixel_size)
    t.left(90)
    t.forward(3 * pixel_size)
    for _ in range(2):
        t.right(90)
        t.forward(pixel_size)
        t.left(90)
        t.forward(2 * pixel_size)
    for i in range(3):
        for _ in range(i + 1):
            t.right(90)
            t.forward(2 * pixel_size)
            t.left(90)
            t.forward(pixel_size)
            t.right(90)
            t.forward(pixel_size)
            t.left(90)
            t.forward(2 * pixel_size)
        t.right(90)
        t.forward(pixel_size)
        t.left(90)
        t.forward(pixel_size)
    t.end_fill()

    # Trous noirs

    t.backward(32 * pixel_size)
    t.left(90)
    t.forward(10 * pixel_size)
    t.color("#000000")
    row_right_squares(t, 1, 3 * pixel_size)
    row_right_squares(t, 1, 3 * pixel_size)
    t.up()
    t.right(90)
    t.forward(7 * pixel_size)
    t.left(90)
    t.forward(2 * pixel_size)
    t.left(180)
    t.down()
    row_right_squares(t, 7, pixel_size)
    t.forward(pixel_size)
    t.left(90)
    t.forward(pixel_size)
    t.left(90)
    row_left_squares(t, 9, pixel_size)
    t.backward(pixel_size)
    t.left(180)
    row_left_squares(t, 7, pixel_size)
